name: CI_CD

on:
  pull_request:
    branches: [master]

jobs:
  build-workflow:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure node version
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
