name: CI_CD

on:
  pull_request:
    branches: [master]

jobs:
  build-workflow:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure node version
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install dependecies
        run: npm ci
      - name: test project
        run: npm test -- --coverage
        env:
          CI: true
      - name: build project
        run: npm run build
